"""baseline

Revision ID: 73147d035bf2
Revises: 
Create Date: 2026-09-09 00:00:33.046489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73147d035bf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_streamer', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('hls_url', sa.String(length=500), nullable=True),
    sa.Column('master_playlist', sa.String(length=500), nullable=True),
    sa.Column('rtmp_url', sa.String(length=500), nullable=True),
    sa.Column('stream_key', sa.String(length=100), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_id'), 'streams', ['id'], unique=False)
    op.create_index(op.f('ix_streams_stream_id'), 'streams', ['stream_id'], unique=True)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_moderated', sa.Boolean(), nullable=True),
    sa.Column('max_message_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_table('stream_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('concurrent_viewers', sa.Integer(), nullable=True),
    sa.Column('peak_viewers', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('unique_viewers', sa.Integer(), nullable=True),
    sa.Column('chat_messages', sa.Integer(), nullable=True),
    sa.Column('emoji_reactions', sa.Integer(), nullable=True),
    sa.Column('average_watch_time', sa.Float(), nullable=True),
    sa.Column('quality_switches', sa.Integer(), nullable=True),
    sa.Column('buffer_events', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('cdn_distribution', sa.JSON(), nullable=True),
    sa.Column('geographic_data', sa.JSON(), nullable=True),
    sa.Column('startup_time', sa.Float(), nullable=True),
    sa.Column('bitrate_stats', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_analytics_id'), 'stream_analytics', ['id'], unique=False)
    op.create_table('stream_qualities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=20), nullable=True),
    sa.Column('playlist_url', sa.String(length=500), nullable=False),
    sa.Column('segment_pattern', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_qualities_id'), 'stream_qualities', ['id'], unique=False)
    op.create_table('viewer_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('join_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('leave_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watch_duration', sa.Float(), nullable=True),
    sa.Column('selected_quality', sa.String(length=20), nullable=True),
    sa.Column('cdn_server', sa.String(length=20), nullable=True),
    sa.Column('buffer_count', sa.Integer(), nullable=True),
    sa.Column('chat_messages_sent', sa.Integer(), nullable=True),
    sa.Column('reactions_sent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewer_sessions_id'), 'viewer_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_viewer_sessions_session_id'), 'viewer_sessions', ['session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('video_timestamp', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_highlighted', sa.Boolean(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_reactions_id'), 'message_reactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_reactions_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_viewer_sessions_session_id'), table_name='viewer_sessions')
    op.drop_index(op.f('ix_viewer_sessions_id'), table_name='viewer_sessions')
    op.drop_table('viewer_sessions')
    op.drop_index(op.f('ix_stream_qualities_id'), table_name='stream_qualities')
    op.drop_table('stream_qualities')
    op.drop_index(op.f('ix_stream_analytics_id'), table_name='stream_analytics')
    op.drop_table('stream_analytics')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_streams_stream_id'), table_name='streams')
    op.drop_index(op.f('ix_streams_id'), table_name='streams')
    op.drop_table('streams')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
